version: "3.9"

services:
  bot:
    build: .
    container_name: bot_service
    command: python3 bot.py
    volumes:
      - .:/app
    restart: always
    networks:
      deputat_net:
        ipv4_address: 192.168.1.10

  savedata:
    build: .
    container_name: savedata_service
    command: python3 parser/saveData.py
    volumes:
      - .:/app
    restart: always
    networks:
      deputat_net:
        ipv4_address: 192.168.1.11

networks:
  deputat_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
